# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('image_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('image_location', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=4096)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectview.Project')),
            ],
            options={
                'db_table': 'project_images',
            },
        ),
    ]
