# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('image_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=64)),
                ('image_location', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'project_images',
            },
        ),
    ]
