# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project_name',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
