# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=64)),
                ('project_description', models.CharField(max_length=1024)),
                ('tech_relm', models.CharField(max_length=64, null=True)),
                ('tech_sub_relm', models.CharField(max_length=64, null=True)),
                ('northstar', models.CharField(max_length=64, null=True)),
                ('round', models.CharField(max_length=6, null=True)),
                ('project_accepted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('relationship_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectview.Project')),
            ],
            options={
                'db_table': 'project_resources',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('resource_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('E', 'Expense'), ('F', 'Funding')], max_length=1)),
                ('transaction_sub_type', models.CharField(choices=[('C', 'IMFS Consulting Fee'), ('A', 'AWS Charges'), ('D', 'Data Expense'), ('S', 'Software Expense'), ('IF', 'Initial Funding'), ('AF', 'Additional Funding')], max_length=2, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectview.Project')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AddField(
            model_name='projectresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectview.Resource'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectview.Resource'),
        ),
    ]
