# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
