# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0002_auto_20171017_1502'),
        ('projectview', '0002_auto_20171017_1529'),
    ]

    operations = [
    ]
