# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 18:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0002_project_project_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_date',
            field=models.DateTimeField(default=datetime.date(2017, 10, 5)),
        ),
    ]
