# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0003_merge_20171023_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech_relm',
            new_name='tech_realm',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tech_sub_relm',
            new_name='tech_sub_realm',
        ),
    ]
