# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0003_project_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 18, 46, 19, 763027, tzinfo=utc)),
        ),
    ]
