# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0004_auto_20171005_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 5, 18, 47, 41, 906159, tzinfo=utc)),
        ),
    ]
