# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 14:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0004_auto_20171024_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 25, 14, 30, 34, 304354, tzinfo=utc)),
        ),
    ]
