# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 18:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0006_auto_20171005_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 5, 18, 56, 16, 739451, tzinfo=utc)),
        ),
    ]
