# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectview', '0008_auto_20171005_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='submission_date',
            field=models.DateField(default=datetime.datetime(2017, 10, 5, 20, 45, 42, 737631, tzinfo=utc)),
        ),
    ]
